unique_ids:
  assets:
    theme.css: ZZT2NUKQSBGYXGWYFMUQENRTE6NMVKAK
  forms:
    ConnectionRow: EBBFONPIF53ZKUB6C2GX2PWQH743HO64
    Connections: VA6QAUCD4C5QY3POXB64WYA2BEJNLK3U
    EmbeddedLayout: 32K5ZCKQOMDW4U3BCGQTZA6ZCQWFC5RN
    Form1: FBYAQNTYCGGOILQD64TUUIJ5Z2J4GEQP
    PermissionRow: QFN4LHVTBGOGWI6CDEJVRQGQLEHSOFY6
  modules:
    host: 4LGXYTAXBT6SEYMUDH4V2GX27SUEFHNH
  scripts: {}
  server_modules:
    _assets: 6C7SA3DNVC5ZBEIN2VHOVG6ZCFBP4Z5B
    access: B2UGZWMLIJGXHCHZYRITROXPTOFMXU6H
    app: 5TUYPK5WWNUSZLYYKMDCV4XNGYDBQHQS
    mcp: LI7Z3QGTKXNQCOKZD4Y7R74RRWA76LVP
