import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
const result = await build({entryPoints: [new URL('./wrapper.js', import.meta.url).pathname], bundle: true, format: 'esm', minify: true, write: false});
const html = (await readFile(new URL('./wrapper.html', import.meta.url), 'utf8')).replace('/* BUNDLE */', () => result.outputFiles[0].text.replaceAll('</script', '<\\/script')).replace('Anvil Dev Updates', 'Anvil app');
const bridge = await readFile(new URL('./frame.js', import.meta.url), 'utf8');
await writeFile(new URL('../server_code/_assets.py', import.meta.url), '# Generated by bridge/build.mjs. Do not edit.\nWRAPPER = ' + JSON.stringify(html) + '\nBRIDGE = ' + JSON.stringify(bridge) + '\n');
